version: '3.4'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 5001:5001
    volumes:
      - ./data:/app/data

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data
